version: '2'
services:
  oto-frontend:
    image: 'sebweitzel/otofrontend:master'
    links: 
     - otoprod
    ports:
     - 3000
  otoprod:
    image: 'sebweitzel/otoproducts:master'
    ports:
     - 5000
    links:
     - mongo
  spring-orders:
    image: 'sebweitzel/springorders:master'
    links:
     - mongo
    ports:
     - 8080
  mongo:
    image: mongo

