apiVersion: v1
kind: Service
metadata:
  name: otofrontend
  labels:
    run: otofrontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: otofrontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: otofrontend
    spec:
      containers:
      - name: otofront
        image: antweiss/otofrontend:master
        ports:
        - containerPort: 3000
